### ISSUE TITLE
Remove requirement of `vidi-metrics` plugin

### ISSUE THREAD

**Issue by mcdonnelldean** [vidi-insights/vidi-metrics-emitter#1]
It is not needed here. This module should maintain its own internal opts.
- remove from all code files
- remove from package.json
- replace vidi.opts with local opts

```
var opts = {
  host: 'localhost',
  port: 5001
}
```

**Comment by mcdonnelldean** [comment]
Is this done?

**Comment by CodeWriterWriter** [comment]
This is done
